import "./globals.css";

export const metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

// Fonts
import { Montserrat, Poppins, Inconsolata } from "next/font/google";

const inconsolata = Inconsolata({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-title",
});
const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-main",
});
const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-body",
});

// Layout
import { Container } from "@/components/layout";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${inconsolata.variable} ${poppins.variable} ${montserrat.variable}`}
      >
        <Container>{children}</Container>
        {/* <div className="bg-primary text-shadow fixed top-0 left-0 z-50 p-4 text-xl font-semibold after:content-['mobile'] sm:after:content-['sm(>640px)'] md:after:content-['md(>768)'] lg:after:content-['lg(>1024px)'] xl:after:content-['xl(>1280px)'] 2xl:after:content-['2xl(>1536px)']"></div> */}
      </body>
    </html>
  );
}
